apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-daemonset
spec:
  selector:
    matchLabels:
      name: my-daemonset
  template:
    metadata:
      labels:
        name: my-daemonset
    spec:
      containers:
        - name: nginx
          image: nginx:1.21.6
          resources:
            limits:
              memory: 50Mi
            requests:
              cpu: 5m
              memory: 50Mi
