apiVersion: v1
kind: Pod
metadata:
  name: water
  labels:
    app: water
spec:
  nodeSelector:
    workshops.de/special-node: "true"
  containers:
    - name: water
      image: nginxdemos/hello:0.3
      resources:
        limits:
          cpu: 25m
        requests:
          cpu: 25m
