apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: alpine
      image: alpine:3.16.0
      command:
        - "/bin/sh"
      args:
        - "-c"
        - "while true; do echo $(date) >> /app/buffer; sleep 5; done;"
      volumeMounts:
        - name: my-volume
          mountPath: /app
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: my-pvc
