apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx-public
  rules:
    - host: app-<user name>.<cluster name>.workshops.isium.de
      http:
        paths:
          - pathType: Prefix
            path: /green
            backend:
              service:
                name: green
                port:
                  number: 80
          - pathType: Prefix
            path: /blue
            backend:
              service:
                name: blue
                port:
                  number: 80
