{
 "title": "USER: <username> / Gitea",
 "description": "Monitor Gitea server",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(gitea_users, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Resident memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"gitea-http\", namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "CPU time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"gitea-http\", namespace=~\"$namespace\"}[5m])"
    }
   ]
  },
  {
   "title": "Open FDS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=\"gitea-http\", namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Number of Accesses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitea_accesses{namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Number of Repositories",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitea_repositories{namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Number of Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitea_users{namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Number of Issues",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitea_issues{namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Number of Actions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitea_actions{namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Number of Labels",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitea_labels{namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Number of Organizations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitea_organizations{namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Number of Teams",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitea_teams{namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Number of Follows",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitea_follows{namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Number of PublicKeys",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitea_publickeys{namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Number of Stars",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitea_stars{namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Number of Webhooks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitea_webhooks{namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Number of Releases",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitea_releases{namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Number of Comments",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitea_comments{namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Number of Milestones",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitea_milestones{namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Number of Watches",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gitea_watches{namespace=~\"$namespace\"}"
    }
   ]
  }
 ]
}