---
ingress:
  enabled: true
  className: nginx-public
  hosts:
    - host: git-<username>.<clustername>.spaces.workshops.de
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

persistence:
  enabled: true
  size: 2Gi

gitea:
  admin:
    username: gitea_admin
    password: foosh5Eeph
    email: "gitea@local.domain"

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        username: gitea
        password: boo1ALohch
        database: gitea
  primary:
    persistence:
      size: 1Gi

postgresql-ha:
  enabled: false

valkey:
  enabled: true

valkey-cluster:
  enabled: false