---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-storageclass-delete
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  zones: europe-west3-c
reclaimPolicy: Delete
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-storageclass-delete
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  zones: europe-west3-c
reclaimPolicy: Retain
