apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-pod
      image: nginxdemos/hello:0.3
      resources:
        limits:
          cpu: 50m
        requests:
          cpu: 50m
  tolerations:
    - key: "foo"
      operator: "Equal"
      value: "bar"
      effect: "NoSchedule"
